### ISSUE TITLE
Branch Deployments

### ISSUE THREAD

**Issue by GrantBirki** [alphagov/consent-api-v1#79]
Hi @andyhd! 👋 

I am one of the core developers behind the branch-deploy Action here at GitHub. I monitor the repo pretty closely to see who all is using it and I'm quite excited to see that UK's government is adopting it in this repo! ⭐ 

Let me know if you need any assistance adopting it or if there are any features that you would like to see come to reality that would make using this Action easier.

I'm also located in the London for the time being too!

Enjoy

- Grant

**Comment by andyhd** [comment]
Hi @GrantBirki 👋 

Thanks for getting in touch. I've managed to get the branch-deploy action working on this repo, although it is still new and I'm tinkering with the workflows pretty constantly. It seems pretty solid at first try!

I'll let you know how I get on with it.

Cheers!
